services:
  catalogue:
    build:
      context: ./catalogue        # points to the folder containing Dockerfile
      dockerfile: Dockerfile      # looks for the file named Dockerfile inside ./catalogue
    image: gattampavan/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongodb          # points to the folder containing Dockerfile
      dockerfile: Dockerfile      # looks for the file named Dockerfile inside ./mongodb
    image: gattampavan/mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true we need to create bridge network manually