services:
  catalogue:
    build: 
      dockerfile: catalogue.Dockerfile # it moves to catalogue directory and looks for Dockerfile
    image: gattampavan/catalogue:1.0.0 # this is equal to docker build -t gattampavan/catalogue:1.0.0 
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - roboshop
  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile # it moves to mongodb directory and looks for Dockerfile
    image: gattampavan/mongodb:1.0.0 # this is equal to docker build -t gattampavan/mongodb:1.0.0 
    container_name: mongodb
    networks:
      - roboshop

networks:
  roboshop:
    driver: bridge
    name: roboshop 
    external: false # if true we need to create bridge network manually 
  